[package]
name = "pcd-parser"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
csv = "1.4.0"
las = { version = "0.9.9", features = ["laz-parallel"] }
pcd-core = { path = "../pcd-core" }
rayon = "1.11.0"

[dev-dependencies]
