[package]
name = "coordinate-transformer"
version.workspace = true
authors.workspace = true
edition.workspace = true

[dependencies]
pcd-core = { path = "../pcd-core" }
proj-sys = "0.27.0"

[features]
bundled-proj = ["proj-sys/bundled_proj"]

[dev-dependencies]
criterion = "0.5"
